export const categories = [
  "Kitchen Remodeling",
  "Bathroom Remodeling",
  "Flooring",
  "Drywall",
  "Painting",
  "Trim and Finish Carpentry",
  "Plumbing",
  "Electrical",
  "General Remodeling",
];
export const scopeTemplates = [
  {
    name: "Kitchen scope checklist",
    category: "Kitchen Remodeling",
    items: [
      "Cabinet installation",
      "Cabinet supply",
      "Quartz countertops",
      "Backsplash",
      "Sink and faucet",
      "Cabinet hardware",
      "Under-cabinet LED lighting",
      "Appliance installation",
      "Demolition",
      "Plumbing adjustments",
      "Electrical adjustments",
      "Disposal and cleanup",
    ],
  },
  {
    name: "Bathroom scope checklist",
    category: "Bathroom Remodeling",
    items: [
      "Demolition",
      "Shower conversion",
      "Waterproofing",
      "Tile installation",
      "Shower pan",
      "Plumbing",
      "Vanity",
      "Countertop",
      "Fixtures",
      "Shower glass",
      "Painting",
      "Cleanup",
    ],
  },
  {
    name: "Flooring scope checklist",
    category: "Flooring",
    items: [
      "Demolition",
      "Subfloor preparation",
      "Leveling",
      "LVP or tile installation",
      "Underlayment",
      "Baseboards",
      "Transitions",
      "Disposal",
    ],
  },
];
// Scope-only templates contain no company pricing. Owner can configure catalog links and units in the database.
